// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (posting_id, status)
VALUES (?, ?)
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type CreateApplicationParams struct {
	PostingID int64          `json:"posting_id"`
	Status    sql.NullString `json:"status"`
}

// Unlike posting_markup, not auto-created for every posting -- an
// application exists only once the user takes an explicit "start
// application" action. status is supplied explicitly by the caller
// (store.CreateApplication passes store.ApplicationStatusStarted.String())
// rather than relying on a DB default -- the initial value is the
// application's decision, not the schema's (see db/migrations/00004_...,
// PR #17 review). notes still relies on its own column default (”).
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication, arg.PostingID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, posting_id, status, notes, created_at, updated_at FROM applications
WHERE posting_id = ?
`

func (q *Queries) GetApplication(ctx context.Context, postingID int64) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, postingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveApplications = `-- name: ListActiveApplications :many
SELECT applications.id, applications.posting_id, applications.status, applications.notes, applications.created_at, applications.updated_at, postings.id, postings.company_id, postings.source, postings.source_id, postings.title, postings.department, postings.team, postings.location, postings.employment_type, postings.workplace_type, postings.description_html, postings.description_text, postings.job_url, postings.application_url, postings.published_at, postings.raw_payload, postings.listing_status, postings.first_seen_at, postings.last_seen_at, postings.created_at, postings.updated_at, companies.name AS company_name
FROM applications
JOIN postings ON postings.id = applications.posting_id
JOIN companies ON companies.id = postings.company_id
WHERE applications.status NOT IN (/*SLICE:terminal_statuses*/?)
ORDER BY applications.updated_at DESC
`

type ListActiveApplicationsRow struct {
	Application Application `json:"application"`
	Posting     Posting     `json:"posting"`
	CompanyName string      `json:"company_name"`
}

// Applications not at a terminal dead-end status, joined with their
// posting and company name -- feeds the active-applications TUI screen
// (#43). Unlike ListInterestedPostings this is an inner join on
// applications (an application always exists for every row here),
// ordered most-recently-changed first so whatever moved last surfaces
// at the top.
//
// sqlc.embed(applications)/sqlc.embed(postings) generate nested
// Application/Posting fields on the row directly from the schema, rather
// than us hand-selecting+aliasing individual columns and reconstructing
// them field-by-field in Go -- verified this works cleanly on this
// engine (sqlite, sqlc v1.31.1) alongside a plain aliased column, one
// inner join, no collisions (see decisions.log, ApplicationView).
//
// sqlc.slice('terminal_statuses') keeps store.TerminalApplicationStatuses
// as the sole source of truth for which statuses are terminal -- no
// status strings are hardcoded here, they're passed in as a query
// parameter at call time (see decisions.log, issue #60). Verified this
// works correctly on this engine with real data before adopting it; the
// one real constraint is that sqlc.slice can't safely combine with other
// bound parameters on sqlite (a documented ordering bug) -- this query
// has none today, but that needs re-verifying if one is ever added.
func (q *Queries) ListActiveApplications(ctx context.Context, terminalStatuses []sql.NullString) ([]ListActiveApplicationsRow, error) {
	query := listActiveApplications
	var queryParams []interface{}
	if len(terminalStatuses) > 0 {
		for _, v := range terminalStatuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", strings.Repeat(",?", len(terminalStatuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveApplicationsRow
	for rows.Next() {
		var i ListActiveApplicationsRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.PostingID,
			&i.Application.Status,
			&i.Application.Notes,
			&i.Application.CreatedAt,
			&i.Application.UpdatedAt,
			&i.Posting.ID,
			&i.Posting.CompanyID,
			&i.Posting.Source,
			&i.Posting.SourceID,
			&i.Posting.Title,
			&i.Posting.Department,
			&i.Posting.Team,
			&i.Posting.Location,
			&i.Posting.EmploymentType,
			&i.Posting.WorkplaceType,
			&i.Posting.DescriptionHtml,
			&i.Posting.DescriptionText,
			&i.Posting.JobUrl,
			&i.Posting.ApplicationUrl,
			&i.Posting.PublishedAt,
			&i.Posting.RawPayload,
			&i.Posting.ListingStatus,
			&i.Posting.FirstSeenAt,
			&i.Posting.LastSeenAt,
			&i.Posting.CreatedAt,
			&i.Posting.UpdatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationNotes = `-- name: UpdateApplicationNotes :one
UPDATE applications
SET notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationNotesParams struct {
	Notes     string `json:"notes"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationNotes, arg.Notes, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	Status    sql.NullString `json:"status"`
	PostingID int64          `json:"posting_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.Status, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
