// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (posting_id)
VALUES (?)
RETURNING id, posting_id, status, notes, created_at, updated_at
`

// Unlike posting_markup, not auto-created for every posting -- an
// application exists only once the user takes an explicit "start
// application" action. Relies on column defaults (status='application_started',
// notes=”).
func (q *Queries) CreateApplication(ctx context.Context, postingID int64) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication, postingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, posting_id, status, notes, created_at, updated_at FROM applications
WHERE posting_id = ?
`

func (q *Queries) GetApplication(ctx context.Context, postingID int64) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, postingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationNotes = `-- name: UpdateApplicationNotes :one
UPDATE applications
SET notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationNotesParams struct {
	Notes     string `json:"notes"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationNotes, arg.Notes, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	Status    string `json:"status"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.Status, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
