// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (posting_id, status)
VALUES (?, ?)
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type CreateApplicationParams struct {
	PostingID int64          `json:"posting_id"`
	Status    sql.NullString `json:"status"`
}

// Unlike posting_markup, not auto-created for every posting -- an
// application exists only once the user takes an explicit "start
// application" action. status is supplied explicitly by the caller
// (store.CreateApplication passes store.ApplicationStatusStarted.String())
// rather than relying on a DB default -- the initial value is the
// application's decision, not the schema's (see db/migrations/00004_...,
// PR #17 review). notes still relies on its own column default (”).
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication, arg.PostingID, arg.Status)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, posting_id, status, notes, created_at, updated_at FROM applications
WHERE posting_id = ?
`

func (q *Queries) GetApplication(ctx context.Context, postingID int64) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, postingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveApplications = `-- name: ListActiveApplications :many
SELECT
    postings.id, postings.company_id, postings.source, postings.source_id, postings.title, postings.department, postings.team, postings.location, postings.employment_type, postings.workplace_type, postings.description_html, postings.description_text, postings.job_url, postings.application_url, postings.published_at, postings.raw_payload, postings.listing_status, postings.first_seen_at, postings.last_seen_at, postings.created_at, postings.updated_at,
    companies.name AS company_name,
    applications.id AS application_id,
    applications.status AS application_status
FROM applications
JOIN postings ON postings.id = applications.posting_id
JOIN companies ON companies.id = postings.company_id
WHERE applications.status NOT IN ('rejected', 'offer_declined')
ORDER BY applications.updated_at DESC
`

type ListActiveApplicationsRow struct {
	ID                int64          `json:"id"`
	CompanyID         int64          `json:"company_id"`
	Source            string         `json:"source"`
	SourceID          string         `json:"source_id"`
	Title             string         `json:"title"`
	Department        sql.NullString `json:"department"`
	Team              sql.NullString `json:"team"`
	Location          sql.NullString `json:"location"`
	EmploymentType    sql.NullString `json:"employment_type"`
	WorkplaceType     sql.NullString `json:"workplace_type"`
	DescriptionHtml   sql.NullString `json:"description_html"`
	DescriptionText   sql.NullString `json:"description_text"`
	JobUrl            sql.NullString `json:"job_url"`
	ApplicationUrl    sql.NullString `json:"application_url"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	RawPayload        string         `json:"raw_payload"`
	ListingStatus     string         `json:"listing_status"`
	FirstSeenAt       time.Time      `json:"first_seen_at"`
	LastSeenAt        time.Time      `json:"last_seen_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CompanyName       string         `json:"company_name"`
	ApplicationID     int64          `json:"application_id"`
	ApplicationStatus sql.NullString `json:"application_status"`
}

// Applications not at a terminal dead-end status (rejected,
// offer_declined), joined with their posting and company name -- feeds
// the active-applications TUI screen (#43). Unlike ListInterestedPostings
// this is an inner join on applications (an application always exists
// for every row here), ordered most-recently-changed first so whatever
// moved last surfaces at the top.
func (q *Queries) ListActiveApplications(ctx context.Context) ([]ListActiveApplicationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveApplicationsRow
	for rows.Next() {
		var i ListActiveApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.SourceID,
			&i.Title,
			&i.Department,
			&i.Team,
			&i.Location,
			&i.EmploymentType,
			&i.WorkplaceType,
			&i.DescriptionHtml,
			&i.DescriptionText,
			&i.JobUrl,
			&i.ApplicationUrl,
			&i.PublishedAt,
			&i.RawPayload,
			&i.ListingStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.ApplicationID,
			&i.ApplicationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationNotes = `-- name: UpdateApplicationNotes :one
UPDATE applications
SET notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationNotesParams struct {
	Notes     string `json:"notes"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationNotes, arg.Notes, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE applications
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING id, posting_id, status, notes, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	Status    sql.NullString `json:"status"`
	PostingID int64          `json:"posting_id"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, updateApplicationStatus, arg.Status, arg.PostingID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
