// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_status_history.sql

package db

import (
	"context"
)

const createApplicationStatusHistory = `-- name: CreateApplicationStatusHistory :exec
INSERT INTO application_status_history (application_id, status, changed_by)
VALUES (?, ?, ?)
`

type CreateApplicationStatusHistoryParams struct {
	ApplicationID int64  `json:"application_id"`
	Status        string `json:"status"`
	ChangedBy     string `json:"changed_by"`
}

// Written only by store.recordApplicationStatus, inside the same
// transaction as the status change it records (#162).
func (q *Queries) CreateApplicationStatusHistory(ctx context.Context, arg CreateApplicationStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createApplicationStatusHistory, arg.ApplicationID, arg.Status, arg.ChangedBy)
	return err
}

const latestApplicationStatusChange = `-- name: LatestApplicationStatusChange :one
SELECT id, application_id, status, changed_at, changed_by FROM application_status_history
WHERE application_id = ?
ORDER BY changed_at DESC, id DESC
LIMIT 1
`

// When the application entered its current status: every status write
// records a row (#162), so the newest is the current status's.
func (q *Queries) LatestApplicationStatusChange(ctx context.Context, applicationID int64) (ApplicationStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, latestApplicationStatusChange, applicationID)
	var i ApplicationStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Status,
		&i.ChangedAt,
		&i.ChangedBy,
	)
	return i, err
}

const listApplicationStatusHistory = `-- name: ListApplicationStatusHistory :many
SELECT id, application_id, status, changed_at, changed_by FROM application_status_history
WHERE application_id = ?
ORDER BY changed_at, id
`

// Oldest first. id breaks ties between changes in the same second
// (CURRENT_TIMESTAMP has one-second resolution).
func (q *Queries) ListApplicationStatusHistory(ctx context.Context, applicationID int64) ([]ApplicationStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listApplicationStatusHistory, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationStatusHistory
	for rows.Next() {
		var i ApplicationStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Status,
			&i.ChangedAt,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
