// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_events.sql

package db

import (
	"context"
)

const changeEventsAfter = `-- name: ChangeEventsAfter :many
SELECT id, table_name, row_id, op, old, new, origin, at FROM change_events
WHERE id > ?
ORDER BY id
`

func (q *Queries) ChangeEventsAfter(ctx context.Context, id int64) ([]ChangeEvent, error) {
	rows, err := q.db.QueryContext(ctx, changeEventsAfter, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeEvent
	for rows.Next() {
		var i ChangeEvent
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RowID,
			&i.Op,
			&i.Old,
			&i.New,
			&i.Origin,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestChangeEventID = `-- name: LatestChangeEventID :one
SELECT CAST(coalesce(max(id), 0) AS INTEGER) AS id FROM change_events
`

func (q *Queries) LatestChangeEventID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestChangeEventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
