// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, source, source_ref)
VALUES (?, ?, ?)
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at
`

type CreateCompanyParams struct {
	Name      string `json:"name"`
	Source    string `json:"source"`
	SourceRef string `json:"source_ref"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.Source, arg.SourceRef)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at FROM companies
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyBySourceAndSourceRef = `-- name: GetCompanyBySourceAndSourceRef :one
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at FROM companies
WHERE source = ? AND source_ref = ?
`

type GetCompanyBySourceAndSourceRefParams struct {
	Source    string `json:"source"`
	SourceRef string `json:"source_ref"`
}

// Deliberately ignores deleted_at: source+source_ref is UNIQUE across all
// rows regardless of soft-delete state, so re-adding a company (CreateCompany)
// needs to find a soft-deleted match too, in order to restore it instead of
// violating the UNIQUE constraint with a duplicate insert.
func (q *Queries) GetCompanyBySourceAndSourceRef(ctx context.Context, arg GetCompanyBySourceAndSourceRefParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyBySourceAndSourceRef, arg.Source, arg.SourceRef)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCompanies = `-- name: ListActiveCompanies :many
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at FROM companies
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListActiveCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCompany = `-- name: RestoreCompany :exec
UPDATE companies
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) RestoreCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreCompany, id)
	return err
}

const restoreCompanyWithName = `-- name: RestoreCompanyWithName :one
UPDATE companies
SET name = ?, deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at
`

type RestoreCompanyWithNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RestoreCompanyWithName(ctx context.Context, arg RestoreCompanyWithNameParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, restoreCompanyWithName, arg.Name, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE companies
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteCompany, id)
	return err
}

const updateCompanyName = `-- name: UpdateCompanyName :one
UPDATE companies
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at
`

type UpdateCompanyNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

// Excludes soft-deleted rows, same guard as GetCompany -- editing a
// deleted company isn't a supported action.
func (q *Queries) UpdateCompanyName(ctx context.Context, arg UpdateCompanyNameParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyName, arg.Name, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
