// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_filters.sql

package db

import (
	"context"
)

const createCompanyFilter = `-- name: CreateCompanyFilter :one
INSERT INTO company_filters (company_id, field, value)
VALUES (?, ?, ?)
RETURNING id, company_id, field, value, created_at
`

type CreateCompanyFilterParams struct {
	CompanyID int64  `json:"company_id"`
	Field     string `json:"field"`
	Value     string `json:"value"`
}

func (q *Queries) CreateCompanyFilter(ctx context.Context, arg CreateCompanyFilterParams) (CompanyFilter, error) {
	row := q.db.QueryRowContext(ctx, createCompanyFilter, arg.CompanyID, arg.Field, arg.Value)
	var i CompanyFilter
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Field,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompanyFilters = `-- name: DeleteCompanyFilters :exec
DELETE FROM company_filters
WHERE company_id = ?
`

func (q *Queries) DeleteCompanyFilters(ctx context.Context, companyID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompanyFilters, companyID)
	return err
}

const listCompanyFilters = `-- name: ListCompanyFilters :many
SELECT id, company_id, field, value, created_at FROM company_filters
WHERE company_id = ?
ORDER BY id
`

func (q *Queries) ListCompanyFilters(ctx context.Context, companyID int64) ([]CompanyFilter, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyFilters, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyFilter
	for rows.Next() {
		var i CompanyFilter
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Field,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
