// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"
	"database/sql"
)

const acquireCompanySyncLease = `-- name: AcquireCompanySyncLease :execrows
UPDATE companies
SET sync_lease_token = ?1, sync_lease_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND (sync_lease_token IS NULL
       OR sync_lease_at < datetime('now', printf('-%d seconds', CAST(?3 AS INTEGER))))
`

type AcquireCompanySyncLeaseParams struct {
	Token         sql.NullString `json:"token"`
	ID            int64          `json:"id"`
	ExpirySeconds int64          `json:"expiry_seconds"`
}

// Takes the company's sync lease if it's free or has expired (see
// store.AcquireSyncLease, #150). Expiry is compared entirely in SQL, so
// both sides are CURRENT_TIMESTAMP-format UTC text.
func (q *Queries) AcquireCompanySyncLease(ctx context.Context, arg AcquireCompanySyncLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireCompanySyncLease, arg.Token, arg.ID, arg.ExpirySeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, source, source_ref)
VALUES (?, ?, ?)
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at
`

type CreateCompanyParams struct {
	Name      string `json:"name"`
	Source    string `json:"source"`
	SourceRef string `json:"source_ref"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, arg.Name, arg.Source, arg.SourceRef)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at FROM companies
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}

const getCompanyBySourceAndSourceRef = `-- name: GetCompanyBySourceAndSourceRef :one
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at FROM companies
WHERE source = ? AND source_ref = ?
`

type GetCompanyBySourceAndSourceRefParams struct {
	Source    string `json:"source"`
	SourceRef string `json:"source_ref"`
}

// Deliberately ignores deleted_at: source+source_ref is UNIQUE across all
// rows regardless of soft-delete state, so re-adding a company (CreateCompany)
// needs to find a soft-deleted match too, in order to restore it instead of
// violating the UNIQUE constraint with a duplicate insert.
func (q *Queries) GetCompanyBySourceAndSourceRef(ctx context.Context, arg GetCompanyBySourceAndSourceRefParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyBySourceAndSourceRef, arg.Source, arg.SourceRef)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}

const listActiveCompanies = `-- name: ListActiveCompanies :many
SELECT id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at FROM companies
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListActiveCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.SourceRef,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.LastFetchedAt,
			&i.SyncLeaseToken,
			&i.SyncLeaseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCompanyFetched = `-- name: MarkCompanyFetched :exec
UPDATE companies
SET last_fetched_at = CURRENT_TIMESTAMP
WHERE id = ?
`

// Records a successful fetch of this company's postings (see sync.SyncCompany).
func (q *Queries) MarkCompanyFetched(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markCompanyFetched, id)
	return err
}

const releaseCompanySyncLease = `-- name: ReleaseCompanySyncLease :exec
UPDATE companies
SET sync_lease_token = NULL, sync_lease_at = NULL
WHERE id = ?1 AND sync_lease_token = ?2
`

type ReleaseCompanySyncLeaseParams struct {
	ID    int64          `json:"id"`
	Token sql.NullString `json:"token"`
}

// Frees the lease only if token still holds it, so a sync whose lease
// expired and was taken over can't release the new holder's.
func (q *Queries) ReleaseCompanySyncLease(ctx context.Context, arg ReleaseCompanySyncLeaseParams) error {
	_, err := q.db.ExecContext(ctx, releaseCompanySyncLease, arg.ID, arg.Token)
	return err
}

const restoreCompany = `-- name: RestoreCompany :exec
UPDATE companies
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) RestoreCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreCompany, id)
	return err
}

const restoreCompanyWithName = `-- name: RestoreCompanyWithName :one
UPDATE companies
SET name = ?, deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at
`

type RestoreCompanyWithNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RestoreCompanyWithName(ctx context.Context, arg RestoreCompanyWithNameParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, restoreCompanyWithName, arg.Name, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :exec
UPDATE companies
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteCompany(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteCompany, id)
	return err
}

const updateCompanyDescription = `-- name: UpdateCompanyDescription :one
UPDATE companies
SET description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at
`

type UpdateCompanyDescriptionParams struct {
	Description string `json:"description"`
	ID          int64  `json:"id"`
}

// Same soft-delete guard as UpdateCompanyName.
func (q *Queries) UpdateCompanyDescription(ctx context.Context, arg UpdateCompanyDescriptionParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyDescription, arg.Description, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}

const updateCompanyName = `-- name: UpdateCompanyName :one
UPDATE companies
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, source, source_ref, deleted_at, created_at, updated_at, description, last_fetched_at, sync_lease_token, sync_lease_at
`

type UpdateCompanyNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

// Excludes soft-deleted rows, same guard as GetCompany -- editing a
// deleted company isn't a supported action.
func (q *Queries) UpdateCompanyName(ctx context.Context, arg UpdateCompanyNameParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, updateCompanyName, arg.Name, arg.ID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Source,
		&i.SourceRef,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.LastFetchedAt,
		&i.SyncLeaseToken,
		&i.SyncLeaseAt,
	)
	return i, err
}
