// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_writes.sql

package db

import (
	"context"
)

const createDocumentWrite = `-- name: CreateDocumentWrite :exec
INSERT INTO document_writes (application_id, document_type, content_sha256, source)
VALUES (?, ?, ?, ?)
`

type CreateDocumentWriteParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
	ContentSha256 string `json:"content_sha256"`
	Source        string `json:"source"`
}

func (q *Queries) CreateDocumentWrite(ctx context.Context, arg CreateDocumentWriteParams) error {
	_, err := q.db.ExecContext(ctx, createDocumentWrite,
		arg.ApplicationID,
		arg.DocumentType,
		arg.ContentSha256,
		arg.Source,
	)
	return err
}

const latestDocumentWrite = `-- name: LatestDocumentWrite :one
SELECT id, application_id, document_type, content_sha256, source, written_at FROM document_writes
WHERE application_id = ? AND document_type = ?
ORDER BY written_at DESC, id DESC
LIMIT 1
`

type LatestDocumentWriteParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
}

// id breaks ties between writes in the same second (CURRENT_TIMESTAMP
// has one-second resolution); AUTOINCREMENT keeps it increasing.
func (q *Queries) LatestDocumentWrite(ctx context.Context, arg LatestDocumentWriteParams) (DocumentWrite, error) {
	row := q.db.QueryRowContext(ctx, latestDocumentWrite, arg.ApplicationID, arg.DocumentType)
	var i DocumentWrite
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentType,
		&i.ContentSha256,
		&i.Source,
		&i.WrittenAt,
	)
	return i, err
}
