// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_exports.sql

package db

import (
	"context"
)

const createDocumentExport = `-- name: CreateDocumentExport :exec
INSERT INTO document_exports (application_id, document_type, content_sha256, path)
VALUES (?, ?, ?, ?)
`

type CreateDocumentExportParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
	ContentSha256 string `json:"content_sha256"`
	Path          string `json:"path"`
}

func (q *Queries) CreateDocumentExport(ctx context.Context, arg CreateDocumentExportParams) error {
	_, err := q.db.ExecContext(ctx, createDocumentExport,
		arg.ApplicationID,
		arg.DocumentType,
		arg.ContentSha256,
		arg.Path,
	)
	return err
}

const deleteDocumentExportsForApplication = `-- name: DeleteDocumentExportsForApplication :exec
DELETE FROM document_exports
WHERE application_id = ?
`

func (q *Queries) DeleteDocumentExportsForApplication(ctx context.Context, applicationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentExportsForApplication, applicationID)
	return err
}

const latestDocumentExport = `-- name: LatestDocumentExport :one
SELECT id, application_id, document_type, content_sha256, path, exported_at FROM document_exports
WHERE application_id = ? AND document_type = ?
ORDER BY exported_at DESC, id DESC
LIMIT 1
`

type LatestDocumentExportParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
}

// id breaks ties between exports in the same second (CURRENT_TIMESTAMP
// has one-second resolution).
func (q *Queries) LatestDocumentExport(ctx context.Context, arg LatestDocumentExportParams) (DocumentExport, error) {
	row := q.db.QueryRowContext(ctx, latestDocumentExport, arg.ApplicationID, arg.DocumentType)
	var i DocumentExport
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentType,
		&i.ContentSha256,
		&i.Path,
		&i.ExportedAt,
	)
	return i, err
}
