// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_reviews.sql

package db

import (
	"context"
)

const countDocumentReviews = `-- name: CountDocumentReviews :one
SELECT COUNT(*) FROM document_reviews
WHERE application_id = ? AND document_type = ?
`

type CountDocumentReviewsParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
}

func (q *Queries) CountDocumentReviews(ctx context.Context, arg CountDocumentReviewsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentReviews, arg.ApplicationID, arg.DocumentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentReview = `-- name: CreateDocumentReview :one
INSERT INTO document_reviews (
    application_id, document_type, cycle, content_snapshot, content_sha256, outcome, notes
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, application_id, document_type, cycle, content_snapshot, content_sha256, outcome, notes, created_at
`

type CreateDocumentReviewParams struct {
	ApplicationID   int64  `json:"application_id"`
	DocumentType    string `json:"document_type"`
	Cycle           int64  `json:"cycle"`
	ContentSnapshot string `json:"content_snapshot"`
	ContentSha256   string `json:"content_sha256"`
	Outcome         string `json:"outcome"`
	Notes           string `json:"notes"`
}

func (q *Queries) CreateDocumentReview(ctx context.Context, arg CreateDocumentReviewParams) (DocumentReview, error) {
	row := q.db.QueryRowContext(ctx, createDocumentReview,
		arg.ApplicationID,
		arg.DocumentType,
		arg.Cycle,
		arg.ContentSnapshot,
		arg.ContentSha256,
		arg.Outcome,
		arg.Notes,
	)
	var i DocumentReview
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.DocumentType,
		&i.Cycle,
		&i.ContentSnapshot,
		&i.ContentSha256,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentReviews = `-- name: ListDocumentReviews :many
SELECT id, application_id, document_type, cycle, content_snapshot, content_sha256, outcome, notes, created_at FROM document_reviews
WHERE application_id = ? AND document_type = ?
ORDER BY cycle DESC
`

type ListDocumentReviewsParams struct {
	ApplicationID int64  `json:"application_id"`
	DocumentType  string `json:"document_type"`
}

// cycle DESC: most recent review first, matching how a human would want
// to read review history (latest verdict up top).
func (q *Queries) ListDocumentReviews(ctx context.Context, arg ListDocumentReviewsParams) ([]DocumentReview, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentReviews, arg.ApplicationID, arg.DocumentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentReview
	for rows.Next() {
		var i DocumentReview
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.DocumentType,
			&i.Cycle,
			&i.ContentSnapshot,
			&i.ContentSha256,
			&i.Outcome,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
