// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interview_stages.sql

package db

import (
	"context"
	"database/sql"
)

const createInterviewStage = `-- name: CreateInterviewStage :one
INSERT INTO interview_stages (posting_id, sequence, name, stage_date, notes)
VALUES (?, ?, ?, ?, ?)
RETURNING id, posting_id, sequence, name, stage_date, outcome, notes, created_at, updated_at
`

type CreateInterviewStageParams struct {
	PostingID int64        `json:"posting_id"`
	Sequence  int64        `json:"sequence"`
	Name      string       `json:"name"`
	StageDate sql.NullTime `json:"stage_date"`
	Notes     string       `json:"notes"`
}

func (q *Queries) CreateInterviewStage(ctx context.Context, arg CreateInterviewStageParams) (InterviewStage, error) {
	row := q.db.QueryRowContext(ctx, createInterviewStage,
		arg.PostingID,
		arg.Sequence,
		arg.Name,
		arg.StageDate,
		arg.Notes,
	)
	var i InterviewStage
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Sequence,
		&i.Name,
		&i.StageDate,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInterviewStage = `-- name: DeleteInterviewStage :exec
DELETE FROM interview_stages
WHERE id = ?
`

func (q *Queries) DeleteInterviewStage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInterviewStage, id)
	return err
}

const listInterviewStagesByPosting = `-- name: ListInterviewStagesByPosting :many
SELECT id, posting_id, sequence, name, stage_date, outcome, notes, created_at, updated_at FROM interview_stages
WHERE posting_id = ?
ORDER BY sequence
`

func (q *Queries) ListInterviewStagesByPosting(ctx context.Context, postingID int64) ([]InterviewStage, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewStagesByPosting, postingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewStage
	for rows.Next() {
		var i InterviewStage
		if err := rows.Scan(
			&i.ID,
			&i.PostingID,
			&i.Sequence,
			&i.Name,
			&i.StageDate,
			&i.Outcome,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewStage = `-- name: UpdateInterviewStage :one
UPDATE interview_stages
SET sequence = ?,
    name = ?,
    stage_date = ?,
    outcome = ?,
    notes = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, posting_id, sequence, name, stage_date, outcome, notes, created_at, updated_at
`

type UpdateInterviewStageParams struct {
	Sequence  int64        `json:"sequence"`
	Name      string       `json:"name"`
	StageDate sql.NullTime `json:"stage_date"`
	Outcome   string       `json:"outcome"`
	Notes     string       `json:"notes"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateInterviewStage(ctx context.Context, arg UpdateInterviewStageParams) (InterviewStage, error) {
	row := q.db.QueryRowContext(ctx, updateInterviewStage,
		arg.Sequence,
		arg.Name,
		arg.StageDate,
		arg.Outcome,
		arg.Notes,
		arg.ID,
	)
	var i InterviewStage
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Sequence,
		&i.Name,
		&i.StageDate,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInterviewStageOutcome = `-- name: UpdateInterviewStageOutcome :one
UPDATE interview_stages
SET outcome = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, posting_id, sequence, name, stage_date, outcome, notes, created_at, updated_at
`

type UpdateInterviewStageOutcomeParams struct {
	Outcome string `json:"outcome"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateInterviewStageOutcome(ctx context.Context, arg UpdateInterviewStageOutcomeParams) (InterviewStage, error) {
	row := q.db.QueryRowContext(ctx, updateInterviewStageOutcome, arg.Outcome, arg.ID)
	var i InterviewStage
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.Sequence,
		&i.Name,
		&i.StageDate,
		&i.Outcome,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
