// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Application struct {
	ID        int64     `json:"id"`
	PostingID int64     `json:"posting_id"`
	Status    string    `json:"status"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Company struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Source    string       `json:"source"`
	SourceRef string       `json:"source_ref"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type CompanyFilter struct {
	ID        int64     `json:"id"`
	CompanyID int64     `json:"company_id"`
	Field     string    `json:"field"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
}

type InterviewStage struct {
	ID            int64        `json:"id"`
	ApplicationID int64        `json:"application_id"`
	Sequence      int64        `json:"sequence"`
	Name          string       `json:"name"`
	StageDate     sql.NullTime `json:"stage_date"`
	Outcome       string       `json:"outcome"`
	Notes         string       `json:"notes"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type Posting struct {
	ID              int64          `json:"id"`
	CompanyID       int64          `json:"company_id"`
	Source          string         `json:"source"`
	SourceID        string         `json:"source_id"`
	Title           string         `json:"title"`
	Department      sql.NullString `json:"department"`
	Team            sql.NullString `json:"team"`
	Location        sql.NullString `json:"location"`
	EmploymentType  sql.NullString `json:"employment_type"`
	WorkplaceType   sql.NullString `json:"workplace_type"`
	DescriptionHtml sql.NullString `json:"description_html"`
	DescriptionText sql.NullString `json:"description_text"`
	JobUrl          sql.NullString `json:"job_url"`
	ApplicationUrl  sql.NullString `json:"application_url"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	RawPayload      string         `json:"raw_payload"`
	ListingStatus   string         `json:"listing_status"`
	FirstSeenAt     time.Time      `json:"first_seen_at"`
	LastSeenAt      time.Time      `json:"last_seen_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type PostingHistory struct {
	ID         int64     `json:"id"`
	PostingID  int64     `json:"posting_id"`
	ChangeType string    `json:"change_type"`
	Snapshot   string    `json:"snapshot"`
	RecordedAt time.Time `json:"recorded_at"`
}

type PostingMarkup struct {
	PostingID    int64        `json:"posting_id"`
	InterestedAt sql.NullTime `json:"interested_at"`
	ArchivedAt   sql.NullTime `json:"archived_at"`
	Notes        string       `json:"notes"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type PostingTag struct {
	PostingID int64 `json:"posting_id"`
	TagID     int64 `json:"tag_id"`
}

type Tag struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
