// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posting_application_forms.sql

package db

import (
	"context"
)

const getPostingApplicationForm = `-- name: GetPostingApplicationForm :one
SELECT posting_id, form, fetched_at FROM posting_application_forms
WHERE posting_id = ?
`

func (q *Queries) GetPostingApplicationForm(ctx context.Context, postingID int64) (PostingApplicationForm, error) {
	row := q.db.QueryRowContext(ctx, getPostingApplicationForm, postingID)
	var i PostingApplicationForm
	err := row.Scan(&i.PostingID, &i.Form, &i.FetchedAt)
	return i, err
}

const savePostingApplicationForm = `-- name: SavePostingApplicationForm :exec
INSERT INTO posting_application_forms (posting_id, form)
VALUES (?, ?)
ON CONFLICT (posting_id) DO UPDATE SET form = excluded.form, fetched_at = CURRENT_TIMESTAMP
`

type SavePostingApplicationFormParams struct {
	PostingID int64  `json:"posting_id"`
	Form      string `json:"form"`
}

// Replaces any earlier fetch of the same posting's form.
func (q *Queries) SavePostingApplicationForm(ctx context.Context, arg SavePostingApplicationFormParams) error {
	_, err := q.db.ExecContext(ctx, savePostingApplicationForm, arg.PostingID, arg.Form)
	return err
}
