// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package db

import (
	"context"
	"database/sql"
)

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings (
    company_id, source, source_id, title, department, team, location,
    employment_type, workplace_type, description_html, description_text,
    job_url, application_url, published_at, raw_payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at
`

type CreatePostingParams struct {
	CompanyID       int64          `json:"company_id"`
	Source          string         `json:"source"`
	SourceID        string         `json:"source_id"`
	Title           string         `json:"title"`
	Department      sql.NullString `json:"department"`
	Team            sql.NullString `json:"team"`
	Location        sql.NullString `json:"location"`
	EmploymentType  sql.NullString `json:"employment_type"`
	WorkplaceType   sql.NullString `json:"workplace_type"`
	DescriptionHtml sql.NullString `json:"description_html"`
	DescriptionText sql.NullString `json:"description_text"`
	JobUrl          sql.NullString `json:"job_url"`
	ApplicationUrl  sql.NullString `json:"application_url"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	RawPayload      string         `json:"raw_payload"`
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, createPosting,
		arg.CompanyID,
		arg.Source,
		arg.SourceID,
		arg.Title,
		arg.Department,
		arg.Team,
		arg.Location,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.JobUrl,
		arg.ApplicationUrl,
		arg.PublishedAt,
		arg.RawPayload,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosting = `-- name: GetPosting :one
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE id = ?
`

func (q *Queries) GetPosting(ctx context.Context, id int64) (Posting, error) {
	row := q.db.QueryRowContext(ctx, getPosting, id)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostingBySourceAndSourceID = `-- name: GetPostingBySourceAndSourceID :one
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE source = ? AND source_id = ?
`

type GetPostingBySourceAndSourceIDParams struct {
	Source   string `json:"source"`
	SourceID string `json:"source_id"`
}

func (q *Queries) GetPostingBySourceAndSourceID(ctx context.Context, arg GetPostingBySourceAndSourceIDParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, getPostingBySourceAndSourceID, arg.Source, arg.SourceID)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctDepartmentsForCompany = `-- name: ListDistinctDepartmentsForCompany :many
SELECT DISTINCT department FROM postings
WHERE company_id = ? AND department IS NOT NULL AND department != ''
ORDER BY department
`

// Keyspace discovery for filter selection: department is a company-
// specific vocabulary (not a fixed enum), so filter values are offered
// from what's actually been ingested, not guessed at.
func (q *Queries) ListDistinctDepartmentsForCompany(ctx context.Context, companyID int64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctDepartmentsForCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var department sql.NullString
		if err := rows.Scan(&department); err != nil {
			return nil, err
		}
		items = append(items, department)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctLocationsForCompany = `-- name: ListDistinctLocationsForCompany :many
SELECT DISTINCT location FROM postings
WHERE company_id = ? AND location IS NOT NULL AND location != ''
ORDER BY location
`

func (q *Queries) ListDistinctLocationsForCompany(ctx context.Context, companyID int64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctLocationsForCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var location sql.NullString
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsByCompany = `-- name: ListPostingsByCompany :many
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE company_id = ?
ORDER BY first_seen_at DESC, id DESC
`

// id DESC is a tiebreaker: a single sync inserts many rows within the same
// CURRENT_TIMESTAMP second (sqlite has only second resolution), so
// first_seen_at alone leaves ties with no guaranteed order.
func (q *Queries) ListPostingsByCompany(ctx context.Context, companyID int64) ([]Posting, error) {
	rows, err := q.db.QueryContext(ctx, listPostingsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.SourceID,
			&i.Title,
			&i.Department,
			&i.Team,
			&i.Location,
			&i.EmploymentType,
			&i.WorkplaceType,
			&i.DescriptionHtml,
			&i.DescriptionText,
			&i.JobUrl,
			&i.ApplicationUrl,
			&i.PublishedAt,
			&i.RawPayload,
			&i.ListingStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostingClosed = `-- name: MarkPostingClosed :exec
UPDATE postings
SET listing_status = 'closed', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPostingClosed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostingClosed, id)
	return err
}

const markPostingReopened = `-- name: MarkPostingReopened :exec
UPDATE postings
SET listing_status = 'open', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPostingReopened(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostingReopened, id)
	return err
}

const updatePosting = `-- name: UpdatePosting :one
UPDATE postings
SET title = ?,
    department = ?,
    team = ?,
    location = ?,
    employment_type = ?,
    workplace_type = ?,
    description_html = ?,
    description_text = ?,
    job_url = ?,
    application_url = ?,
    published_at = ?,
    raw_payload = ?,
    last_seen_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at
`

type UpdatePostingParams struct {
	Title           string         `json:"title"`
	Department      sql.NullString `json:"department"`
	Team            sql.NullString `json:"team"`
	Location        sql.NullString `json:"location"`
	EmploymentType  sql.NullString `json:"employment_type"`
	WorkplaceType   sql.NullString `json:"workplace_type"`
	DescriptionHtml sql.NullString `json:"description_html"`
	DescriptionText sql.NullString `json:"description_text"`
	JobUrl          sql.NullString `json:"job_url"`
	ApplicationUrl  sql.NullString `json:"application_url"`
	PublishedAt     sql.NullTime   `json:"published_at"`
	RawPayload      string         `json:"raw_payload"`
	ID              int64          `json:"id"`
}

// Updates ingested content fields only. Deliberately does not touch
// listing_status: transitions between open/closed are explicit domain
// decisions (see MarkPostingClosed/MarkPostingReopened), not a side effect
// of re-ingesting content. Does not touch company_id: a given (source,
// source_id) is assumed to belong to the same company for its lifetime.
func (q *Queries) UpdatePosting(ctx context.Context, arg UpdatePostingParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, updatePosting,
		arg.Title,
		arg.Department,
		arg.Team,
		arg.Location,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.JobUrl,
		arg.ApplicationUrl,
		arg.PublishedAt,
		arg.RawPayload,
		arg.ID,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
