// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posting_markup.sql

package db

import (
	"context"
)

const createPostingMarkup = `-- name: CreatePostingMarkup :one
INSERT INTO posting_markup (posting_id)
VALUES (?)
RETURNING posting_id, user_status, notes, created_at, updated_at
`

// Not exposed directly on the Store API: every posting must have exactly
// one markup row, so Store creates it as part of UpsertPosting rather than
// leaving callers to remember a second call. Relies on column defaults
// (user_status='new', notes=”).
func (q *Queries) CreatePostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, createPostingMarkup, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.UserStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostingMarkup = `-- name: GetPostingMarkup :one
SELECT posting_id, user_status, notes, created_at, updated_at FROM posting_markup
WHERE posting_id = ?
`

func (q *Queries) GetPostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, getPostingMarkup, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.UserStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePostingMarkupNotes = `-- name: UpdatePostingMarkupNotes :one
UPDATE posting_markup
SET notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, user_status, notes, created_at, updated_at
`

type UpdatePostingMarkupNotesParams struct {
	Notes     string `json:"notes"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdatePostingMarkupNotes(ctx context.Context, arg UpdatePostingMarkupNotesParams) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, updatePostingMarkupNotes, arg.Notes, arg.PostingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.UserStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePostingMarkupStatus = `-- name: UpdatePostingMarkupStatus :one
UPDATE posting_markup
SET user_status = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, user_status, notes, created_at, updated_at
`

type UpdatePostingMarkupStatusParams struct {
	UserStatus string `json:"user_status"`
	PostingID  int64  `json:"posting_id"`
}

func (q *Queries) UpdatePostingMarkupStatus(ctx context.Context, arg UpdatePostingMarkupStatusParams) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, updatePostingMarkupStatus, arg.UserStatus, arg.PostingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.UserStatus,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
