// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const closePostingIfOpen = `-- name: ClosePostingIfOpen :execrows
UPDATE postings
SET listing_status = 'closed', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND listing_status = 'open'
`

// Conditional, unlike MarkPostingClosed: 0 rows affected means the
// posting was already closed (e.g. by an overlapping sync), so the
// caller records nothing (see store.ClosePosting, #147).
func (q *Queries) ClosePostingIfOpen(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, closePostingIfOpen, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOpenPostingsByCompany = `-- name: CountOpenPostingsByCompany :many
SELECT postings.company_id, COUNT(*) AS open_postings
FROM postings
JOIN posting_markup ON posting_markup.posting_id = postings.id
WHERE postings.listing_status = 'open'
  AND posting_markup.archived_at IS NULL
GROUP BY postings.company_id
`

type CountOpenPostingsByCompanyRow struct {
	CompanyID    int64 `json:"company_id"`
	OpenPostings int64 `json:"open_postings"`
}

// Per-company count of what a company's posting list shows by default:
// listings still open on the job board that the user hasn't archived.
// Feeds the company list's "Open" column. Doesn't apply company_filters:
// postings are already gated by filters at ingestion, and a filter added
// later only narrows the posting list's display, not this count.
func (q *Queries) CountOpenPostingsByCompany(ctx context.Context) ([]CountOpenPostingsByCompanyRow, error) {
	rows, err := q.db.QueryContext(ctx, countOpenPostingsByCompany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenPostingsByCompanyRow
	for rows.Next() {
		var i CountOpenPostingsByCompanyRow
		if err := rows.Scan(&i.CompanyID, &i.OpenPostings); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings (
    company_id, source, source_id, title, department, team, location,
    employment_type, workplace_type, description_html, description_text,
    job_url, application_url, published_at, raw_payload
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at
`

type CreatePostingParams struct {
	CompanyID       int64        `json:"company_id"`
	Source          string       `json:"source"`
	SourceID        string       `json:"source_id"`
	Title           string       `json:"title"`
	Department      string       `json:"department"`
	Team            string       `json:"team"`
	Location        string       `json:"location"`
	EmploymentType  string       `json:"employment_type"`
	WorkplaceType   string       `json:"workplace_type"`
	DescriptionHtml string       `json:"description_html"`
	DescriptionText string       `json:"description_text"`
	JobUrl          string       `json:"job_url"`
	ApplicationUrl  string       `json:"application_url"`
	PublishedAt     sql.NullTime `json:"published_at"`
	RawPayload      string       `json:"raw_payload"`
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, createPosting,
		arg.CompanyID,
		arg.Source,
		arg.SourceID,
		arg.Title,
		arg.Department,
		arg.Team,
		arg.Location,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.JobUrl,
		arg.ApplicationUrl,
		arg.PublishedAt,
		arg.RawPayload,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPosting = `-- name: GetPosting :one
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE id = ?
`

func (q *Queries) GetPosting(ctx context.Context, id int64) (Posting, error) {
	row := q.db.QueryRowContext(ctx, getPosting, id)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostingBySourceAndSourceID = `-- name: GetPostingBySourceAndSourceID :one
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE source = ? AND source_id = ?
`

type GetPostingBySourceAndSourceIDParams struct {
	Source   string `json:"source"`
	SourceID string `json:"source_id"`
}

func (q *Queries) GetPostingBySourceAndSourceID(ctx context.Context, arg GetPostingBySourceAndSourceIDParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, getPostingBySourceAndSourceID, arg.Source, arg.SourceID)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctDepartmentsForCompany = `-- name: ListDistinctDepartmentsForCompany :many
SELECT DISTINCT department FROM postings
WHERE company_id = ? AND department != ''
ORDER BY department
`

// Keyspace discovery for filter selection: department is a company-
// specific vocabulary (not a fixed enum), so filter values are offered
// from what's actually been ingested, not guessed at. No "IS NOT NULL"
// check needed -- department is NOT NULL DEFAULT ” (see decisions.log,
// #74), so excluding ” is the only filter required.
func (q *Queries) ListDistinctDepartmentsForCompany(ctx context.Context, companyID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctDepartmentsForCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var department string
		if err := rows.Scan(&department); err != nil {
			return nil, err
		}
		items = append(items, department)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctLocationsForCompany = `-- name: ListDistinctLocationsForCompany :many
SELECT DISTINCT location FROM postings
WHERE company_id = ? AND location != ''
ORDER BY location
`

func (q *Queries) ListDistinctLocationsForCompany(ctx context.Context, companyID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctLocationsForCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterestedPostings = `-- name: ListInterestedPostings :many
SELECT
    postings.id, postings.company_id, postings.source, postings.source_id, postings.title, postings.department, postings.team, postings.location, postings.employment_type, postings.workplace_type, postings.description_html, postings.description_text, postings.job_url, postings.application_url, postings.published_at, postings.raw_payload, postings.listing_status, postings.first_seen_at, postings.last_seen_at, postings.created_at, postings.updated_at,
    companies.name AS company_name,
    applications.id AS application_id,
    applications.status AS application_status
FROM postings
JOIN posting_markup ON posting_markup.posting_id = postings.id
JOIN companies ON companies.id = postings.company_id
LEFT JOIN applications ON applications.posting_id = postings.id
WHERE posting_markup.interested_at IS NOT NULL
  AND posting_markup.archived_at IS NULL
  AND (applications.id IS NULL OR applications.status NOT IN (/*SLICE:terminal_statuses*/?))
ORDER BY posting_markup.interested_at DESC
`

type ListInterestedPostingsRow struct {
	Posting           Posting        `json:"posting"`
	CompanyName       string         `json:"company_name"`
	ApplicationID     sql.NullInt64  `json:"application_id"`
	ApplicationStatus sql.NullString `json:"application_status"`
}

// Postings the user has flagged interested and not archived, joined with
// their company name and -- if one has been started -- their
// application's id and status. Feeds the stage package's discovery of
// work for the external-agent hand-off mechanism (see stage.List).
//
// sqlc.embed(postings) for the always-present side (postings is inner-
// joined via posting_markup, never nullable here) -- same reasoning as
// ListActiveApplications (see decisions.log, ApplicationView). Deliberately
// NOT sqlc.embed(applications): that side is LEFT JOINed (an application
// may not exist yet) and sqlc.embed has a documented bug scanning a NULL
// embedded struct on sqlite (sqlc-dev/sqlc#2997) -- kept as individually
// aliased nullable columns, handled by the existing sql.NullInt64/
// sql.NullString .Valid checks in interestedPostingFromRow.
//
// Postings whose application is at a terminal status are excluded: a
// dead-end application isn't drafting work (#121). Same sqlc.slice
// approach as ListActiveApplications, so store.TerminalApplicationStatuses
// stays the sole source of truth for "terminal" -- including its caveat
// that sqlc.slice can't safely combine with other bound parameters on
// sqlite; this query has none. The applications.id IS NULL branch keeps
// postings with no application yet, which the LEFT JOIN yields as NULLs.
func (q *Queries) ListInterestedPostings(ctx context.Context, terminalStatuses []sql.NullString) ([]ListInterestedPostingsRow, error) {
	query := listInterestedPostings
	var queryParams []interface{}
	if len(terminalStatuses) > 0 {
		for _, v := range terminalStatuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", strings.Repeat(",?", len(terminalStatuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:terminal_statuses*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInterestedPostingsRow
	for rows.Next() {
		var i ListInterestedPostingsRow
		if err := rows.Scan(
			&i.Posting.ID,
			&i.Posting.CompanyID,
			&i.Posting.Source,
			&i.Posting.SourceID,
			&i.Posting.Title,
			&i.Posting.Department,
			&i.Posting.Team,
			&i.Posting.Location,
			&i.Posting.EmploymentType,
			&i.Posting.WorkplaceType,
			&i.Posting.DescriptionHtml,
			&i.Posting.DescriptionText,
			&i.Posting.JobUrl,
			&i.Posting.ApplicationUrl,
			&i.Posting.PublishedAt,
			&i.Posting.RawPayload,
			&i.Posting.ListingStatus,
			&i.Posting.FirstSeenAt,
			&i.Posting.LastSeenAt,
			&i.Posting.CreatedAt,
			&i.Posting.UpdatedAt,
			&i.CompanyName,
			&i.ApplicationID,
			&i.ApplicationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPostingIDsByCompany = `-- name: ListOpenPostingIDsByCompany :many
SELECT id FROM postings
WHERE company_id = ? AND listing_status = 'open'
ORDER BY id
`

// What store.SoftDeleteCompany closes: a deleted company is never synced
// again, so nothing else would ever close these (#178).
func (q *Queries) ListOpenPostingIDsByCompany(ctx context.Context, companyID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPostingIDsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostingsByCompany = `-- name: ListPostingsByCompany :many
SELECT id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at FROM postings
WHERE company_id = ?
ORDER BY first_seen_at DESC, id DESC
`

// id DESC is a tiebreaker: a single sync inserts many rows within the same
// CURRENT_TIMESTAMP second (sqlite has only second resolution), so
// first_seen_at alone leaves ties with no guaranteed order.
func (q *Queries) ListPostingsByCompany(ctx context.Context, companyID int64) ([]Posting, error) {
	rows, err := q.db.QueryContext(ctx, listPostingsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Source,
			&i.SourceID,
			&i.Title,
			&i.Department,
			&i.Team,
			&i.Location,
			&i.EmploymentType,
			&i.WorkplaceType,
			&i.DescriptionHtml,
			&i.DescriptionText,
			&i.JobUrl,
			&i.ApplicationUrl,
			&i.PublishedAt,
			&i.RawPayload,
			&i.ListingStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostingClosed = `-- name: MarkPostingClosed :exec
UPDATE postings
SET listing_status = 'closed', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPostingClosed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostingClosed, id)
	return err
}

const markPostingReopened = `-- name: MarkPostingReopened :exec
UPDATE postings
SET listing_status = 'open', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPostingReopened(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPostingReopened, id)
	return err
}

const markPostingsSeen = `-- name: MarkPostingsSeen :exec
UPDATE postings
SET last_seen_at = CURRENT_TIMESTAMP
WHERE id IN (/*SLICE:ids*/?)
`

// Records that a sync saw these postings on their board (#176). Not a
// content change: updated_at and posting_history are left alone. The
// slice is the only parameter, so sqlc.slice's ordering bug with other
// bound parameters (see ListActiveApplications) doesn't apply.
func (q *Queries) MarkPostingsSeen(ctx context.Context, ids []int64) error {
	query := markPostingsSeen
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const reopenPostingIfClosed = `-- name: ReopenPostingIfClosed :execrows
UPDATE postings
SET listing_status = 'open', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND listing_status = 'closed'
`

// Conditional, unlike MarkPostingReopened: 0 rows affected means the
// posting was already open again (e.g. reopened by an overlapping sync),
// so the caller records nothing (see store.ReopenPosting, #148).
func (q *Queries) ReopenPostingIfClosed(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, reopenPostingIfClosed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchPostingsByID = `-- name: SearchPostingsByID :many
SELECT m.id, m.title, m.department, m.location, m.workplace_type, m.application_url, m.listing_status, m.company_name, m.interested_at, m.archived_at, m.application_id, m.application_status, m.published_at, m.application_notes, m.total
FROM (
    SELECT
        postings.id,
        postings.title,
        postings.department,
        postings.location,
        postings.workplace_type,
        postings.application_url,
        postings.listing_status,
        companies.name AS company_name,
        posting_markup.interested_at,
        posting_markup.archived_at,
        applications.id AS application_id,
        applications.status AS application_status,
        postings.published_at,
        applications.notes AS application_notes,
        COUNT(*) OVER () AS total
    FROM postings
    JOIN companies ON companies.id = postings.company_id
    LEFT JOIN posting_markup ON posting_markup.posting_id = postings.id
    LEFT JOIN applications ON applications.posting_id = postings.id
    WHERE companies.deleted_at IS NULL
      AND (?1 IS NULL OR postings.company_id = ?1)
      AND (?2 IS NULL OR postings.listing_status = ?2)
      AND (?3 OR posting_markup.archived_at IS NULL)
      AND (?4 IS NULL OR (applications.id IS NOT NULL) = ?4)
      AND (?5 IS NULL OR (posting_markup.interested_at IS NOT NULL) = ?5)
      AND (?6 IS NULL OR applications.status IN (SELECT value FROM json_each(?6)))
) AS m
WHERE ?7 IS NULL OR m.id > ?7
ORDER BY m.id
LIMIT ?8
`

type SearchPostingsByIDParams struct {
	CompanyID       interface{} `json:"company_id"`
	ListingStatus   interface{} `json:"listing_status"`
	IncludeArchived interface{} `json:"include_archived"`
	HasApplication  interface{} `json:"has_application"`
	Interested      interface{} `json:"interested"`
	Statuses        interface{} `json:"statuses"`
	AfterID         interface{} `json:"after_id"`
	MaxRows         int64       `json:"max_rows"`
}

type SearchPostingsByIDRow struct {
	ID                int64          `json:"id"`
	Title             string         `json:"title"`
	Department        string         `json:"department"`
	Location          string         `json:"location"`
	WorkplaceType     string         `json:"workplace_type"`
	ApplicationUrl    string         `json:"application_url"`
	ListingStatus     string         `json:"listing_status"`
	CompanyName       string         `json:"company_name"`
	InterestedAt      sql.NullTime   `json:"interested_at"`
	ArchivedAt        sql.NullTime   `json:"archived_at"`
	ApplicationID     sql.NullInt64  `json:"application_id"`
	ApplicationStatus sql.NullString `json:"application_status"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	ApplicationNotes  sql.NullString `json:"application_notes"`
	Total             int64          `json:"total"`
}

// One page of the postings matching every given filter, in posting ID
// order, after an optional cursor ID (#218, RFC 0006). NULL means "don't
// filter on this". Postings of a company the user deleted are never
// included.
//
// The inner query applies the filters and counts every match
// (COUNT(*) OVER ()); the outer one applies the keyset condition and the
// LIMIT. So total is the whole result's size on every page, while only
// max_rows rows ever leave the database.
//
// Application statuses come in as one JSON array read with json_each,
// not sqlc.slice, which can't be mixed with other bound parameters on
// sqlite (see ListActiveApplications). Summary columns only (#117); the
// application side is individually aliased nullable columns, not
// sqlc.embed (see ListInterestedPostings).
func (q *Queries) SearchPostingsByID(ctx context.Context, arg SearchPostingsByIDParams) ([]SearchPostingsByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostingsByID,
		arg.CompanyID,
		arg.ListingStatus,
		arg.IncludeArchived,
		arg.HasApplication,
		arg.Interested,
		arg.Statuses,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostingsByIDRow
	for rows.Next() {
		var i SearchPostingsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.WorkplaceType,
			&i.ApplicationUrl,
			&i.ListingStatus,
			&i.CompanyName,
			&i.InterestedAt,
			&i.ArchivedAt,
			&i.ApplicationID,
			&i.ApplicationStatus,
			&i.PublishedAt,
			&i.ApplicationNotes,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostingsByIDDesc = `-- name: SearchPostingsByIDDesc :many
SELECT m.id, m.title, m.department, m.location, m.workplace_type, m.application_url, m.listing_status, m.company_name, m.interested_at, m.archived_at, m.application_id, m.application_status, m.published_at, m.application_notes, m.total
FROM (
    SELECT
        postings.id,
        postings.title,
        postings.department,
        postings.location,
        postings.workplace_type,
        postings.application_url,
        postings.listing_status,
        companies.name AS company_name,
        posting_markup.interested_at,
        posting_markup.archived_at,
        applications.id AS application_id,
        applications.status AS application_status,
        postings.published_at,
        applications.notes AS application_notes,
        COUNT(*) OVER () AS total
    FROM postings
    JOIN companies ON companies.id = postings.company_id
    LEFT JOIN posting_markup ON posting_markup.posting_id = postings.id
    LEFT JOIN applications ON applications.posting_id = postings.id
    WHERE companies.deleted_at IS NULL
      AND (?1 IS NULL OR postings.company_id = ?1)
      AND (?2 IS NULL OR postings.listing_status = ?2)
      AND (?3 OR posting_markup.archived_at IS NULL)
      AND (?4 IS NULL OR (applications.id IS NOT NULL) = ?4)
      AND (?5 IS NULL OR (posting_markup.interested_at IS NOT NULL) = ?5)
      AND (?6 IS NULL OR applications.status IN (SELECT value FROM json_each(?6)))
) AS m
WHERE ?7 IS NULL OR m.id < ?7
ORDER BY m.id DESC
LIMIT ?8
`

type SearchPostingsByIDDescParams struct {
	CompanyID       interface{} `json:"company_id"`
	ListingStatus   interface{} `json:"listing_status"`
	IncludeArchived interface{} `json:"include_archived"`
	HasApplication  interface{} `json:"has_application"`
	Interested      interface{} `json:"interested"`
	Statuses        interface{} `json:"statuses"`
	BeforeID        interface{} `json:"before_id"`
	MaxRows         int64       `json:"max_rows"`
}

type SearchPostingsByIDDescRow struct {
	ID                int64          `json:"id"`
	Title             string         `json:"title"`
	Department        string         `json:"department"`
	Location          string         `json:"location"`
	WorkplaceType     string         `json:"workplace_type"`
	ApplicationUrl    string         `json:"application_url"`
	ListingStatus     string         `json:"listing_status"`
	CompanyName       string         `json:"company_name"`
	InterestedAt      sql.NullTime   `json:"interested_at"`
	ArchivedAt        sql.NullTime   `json:"archived_at"`
	ApplicationID     sql.NullInt64  `json:"application_id"`
	ApplicationStatus sql.NullString `json:"application_status"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	ApplicationNotes  sql.NullString `json:"application_notes"`
	Total             int64          `json:"total"`
}

// SearchPostingsByID newest first: the same filters, in descending posting
// ID order, before an optional cursor ID (#223). The filters must stay
// identical to SearchPostingsByID's; a test checks every order matches the
// same postings. NULL means "don't
// filter on this". Postings of a company the user deleted are never
// included.
//
// The inner query applies the filters and counts every match
// (COUNT(*) OVER ()); the outer one applies the keyset condition and the
// LIMIT. So total is the whole result's size on every page, while only
// max_rows rows ever leave the database.
//
// Application statuses come in as one JSON array read with json_each,
// not sqlc.slice, which can't be mixed with other bound parameters on
// sqlite (see ListActiveApplications). Summary columns only (#117); the
// application side is individually aliased nullable columns, not
// sqlc.embed (see ListInterestedPostings).
func (q *Queries) SearchPostingsByIDDesc(ctx context.Context, arg SearchPostingsByIDDescParams) ([]SearchPostingsByIDDescRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostingsByIDDesc,
		arg.CompanyID,
		arg.ListingStatus,
		arg.IncludeArchived,
		arg.HasApplication,
		arg.Interested,
		arg.Statuses,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostingsByIDDescRow
	for rows.Next() {
		var i SearchPostingsByIDDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.WorkplaceType,
			&i.ApplicationUrl,
			&i.ListingStatus,
			&i.CompanyName,
			&i.InterestedAt,
			&i.ArchivedAt,
			&i.ApplicationID,
			&i.ApplicationStatus,
			&i.PublishedAt,
			&i.ApplicationNotes,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostingsByPublishedDesc = `-- name: SearchPostingsByPublishedDesc :many
SELECT m.id, m.title, m.department, m.location, m.workplace_type, m.application_url, m.listing_status, m.company_name, m.interested_at, m.archived_at, m.application_id, m.application_status, m.published_at, m.application_notes, m.total
FROM (
    SELECT
        postings.id,
        postings.title,
        postings.department,
        postings.location,
        postings.workplace_type,
        postings.application_url,
        postings.listing_status,
        companies.name AS company_name,
        posting_markup.interested_at,
        posting_markup.archived_at,
        applications.id AS application_id,
        applications.status AS application_status,
        postings.published_at,
        applications.notes AS application_notes,
        COUNT(*) OVER () AS total
    FROM postings
    JOIN companies ON companies.id = postings.company_id
    LEFT JOIN posting_markup ON posting_markup.posting_id = postings.id
    LEFT JOIN applications ON applications.posting_id = postings.id
    WHERE companies.deleted_at IS NULL
      AND (?1 IS NULL OR postings.company_id = ?1)
      AND (?2 IS NULL OR postings.listing_status = ?2)
      AND (?3 OR posting_markup.archived_at IS NULL)
      AND (?4 IS NULL OR (applications.id IS NOT NULL) = ?4)
      AND (?5 IS NULL OR (posting_markup.interested_at IS NOT NULL) = ?5)
      AND (?6 IS NULL OR applications.status IN (SELECT value FROM json_each(?6)))
) AS m
WHERE ?7 IS NULL
   OR (?8 IS NOT NULL
       AND (m.published_at IS NULL
            OR m.published_at < ?8
            OR (m.published_at = ?8 AND m.id < ?7)))
   OR (?8 IS NULL AND m.published_at IS NULL AND m.id < ?7)
ORDER BY m.published_at IS NULL, m.published_at DESC, m.id DESC
LIMIT ?9
`

type SearchPostingsByPublishedDescParams struct {
	CompanyID       interface{} `json:"company_id"`
	ListingStatus   interface{} `json:"listing_status"`
	IncludeArchived interface{} `json:"include_archived"`
	HasApplication  interface{} `json:"has_application"`
	Interested      interface{} `json:"interested"`
	Statuses        interface{} `json:"statuses"`
	CursorID        interface{} `json:"cursor_id"`
	CursorPublished interface{} `json:"cursor_published"`
	MaxRows         int64       `json:"max_rows"`
}

type SearchPostingsByPublishedDescRow struct {
	ID                int64          `json:"id"`
	Title             string         `json:"title"`
	Department        string         `json:"department"`
	Location          string         `json:"location"`
	WorkplaceType     string         `json:"workplace_type"`
	ApplicationUrl    string         `json:"application_url"`
	ListingStatus     string         `json:"listing_status"`
	CompanyName       string         `json:"company_name"`
	InterestedAt      sql.NullTime   `json:"interested_at"`
	ArchivedAt        sql.NullTime   `json:"archived_at"`
	ApplicationID     sql.NullInt64  `json:"application_id"`
	ApplicationStatus sql.NullString `json:"application_status"`
	PublishedAt       sql.NullTime   `json:"published_at"`
	ApplicationNotes  sql.NullString `json:"application_notes"`
	Total             int64          `json:"total"`
}

// SearchPostingsByID newest on the board first (#224): the same filters,
// ordered by published_at descending, then posting ID descending, with
// postings that have no published_at last (by ID, descending). The
// filters must stay identical to SearchPostingsByID's; a test checks every
// order matches the same postings. NULL means "don't filter on this".
//
// The cursor is the previous page's last row: cursor_published (NULL when
// that row had no published_at) and cursor_id. published_at is stored as
// UTC text in one format with trailing fractional zeros trimmed (00012),
// so text order is time order, and a bound time.Time is formatted the
// same way by the connection store.Open makes. Postings of a company
// the user deleted are never included.
//
// The inner query applies the filters and counts every match
// (COUNT(*) OVER ()); the outer one applies the keyset condition and the
// LIMIT. So total is the whole result's size on every page, while only
// max_rows rows ever leave the database.
//
// Application statuses come in as one JSON array read with json_each,
// not sqlc.slice, which can't be mixed with other bound parameters on
// sqlite (see ListActiveApplications). Summary columns only (#117); the
// application side is individually aliased nullable columns, not
// sqlc.embed (see ListInterestedPostings).
func (q *Queries) SearchPostingsByPublishedDesc(ctx context.Context, arg SearchPostingsByPublishedDescParams) ([]SearchPostingsByPublishedDescRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPostingsByPublishedDesc,
		arg.CompanyID,
		arg.ListingStatus,
		arg.IncludeArchived,
		arg.HasApplication,
		arg.Interested,
		arg.Statuses,
		arg.CursorID,
		arg.CursorPublished,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostingsByPublishedDescRow
	for rows.Next() {
		var i SearchPostingsByPublishedDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Department,
			&i.Location,
			&i.WorkplaceType,
			&i.ApplicationUrl,
			&i.ListingStatus,
			&i.CompanyName,
			&i.InterestedAt,
			&i.ArchivedAt,
			&i.ApplicationID,
			&i.ApplicationStatus,
			&i.PublishedAt,
			&i.ApplicationNotes,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosting = `-- name: UpdatePosting :one
UPDATE postings
SET title = ?,
    department = ?,
    team = ?,
    location = ?,
    employment_type = ?,
    workplace_type = ?,
    description_html = ?,
    description_text = ?,
    job_url = ?,
    application_url = ?,
    published_at = ?,
    raw_payload = ?,
    last_seen_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, company_id, source, source_id, title, department, team, location, employment_type, workplace_type, description_html, description_text, job_url, application_url, published_at, raw_payload, listing_status, first_seen_at, last_seen_at, created_at, updated_at
`

type UpdatePostingParams struct {
	Title           string       `json:"title"`
	Department      string       `json:"department"`
	Team            string       `json:"team"`
	Location        string       `json:"location"`
	EmploymentType  string       `json:"employment_type"`
	WorkplaceType   string       `json:"workplace_type"`
	DescriptionHtml string       `json:"description_html"`
	DescriptionText string       `json:"description_text"`
	JobUrl          string       `json:"job_url"`
	ApplicationUrl  string       `json:"application_url"`
	PublishedAt     sql.NullTime `json:"published_at"`
	RawPayload      string       `json:"raw_payload"`
	ID              int64        `json:"id"`
}

// Updates ingested content fields only. Deliberately does not touch
// listing_status: transitions between open/closed are explicit domain
// decisions (see MarkPostingClosed/MarkPostingReopened), not a side effect
// of re-ingesting content. Does not touch company_id: a given (source,
// source_id) is assumed to belong to the same company for its lifetime.
func (q *Queries) UpdatePosting(ctx context.Context, arg UpdatePostingParams) (Posting, error) {
	row := q.db.QueryRowContext(ctx, updatePosting,
		arg.Title,
		arg.Department,
		arg.Team,
		arg.Location,
		arg.EmploymentType,
		arg.WorkplaceType,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.JobUrl,
		arg.ApplicationUrl,
		arg.PublishedAt,
		arg.RawPayload,
		arg.ID,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Source,
		&i.SourceID,
		&i.Title,
		&i.Department,
		&i.Team,
		&i.Location,
		&i.EmploymentType,
		&i.WorkplaceType,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.JobUrl,
		&i.ApplicationUrl,
		&i.PublishedAt,
		&i.RawPayload,
		&i.ListingStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
