// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posting_history.sql

package db

import (
	"context"
)

const createPostingHistory = `-- name: CreatePostingHistory :one
INSERT INTO posting_history (posting_id, change_type, snapshot)
VALUES (?, ?, ?)
RETURNING id, posting_id, change_type, snapshot, recorded_at
`

type CreatePostingHistoryParams struct {
	PostingID  int64  `json:"posting_id"`
	ChangeType string `json:"change_type"`
	Snapshot   string `json:"snapshot"`
}

func (q *Queries) CreatePostingHistory(ctx context.Context, arg CreatePostingHistoryParams) (PostingHistory, error) {
	row := q.db.QueryRowContext(ctx, createPostingHistory, arg.PostingID, arg.ChangeType, arg.Snapshot)
	var i PostingHistory
	err := row.Scan(
		&i.ID,
		&i.PostingID,
		&i.ChangeType,
		&i.Snapshot,
		&i.RecordedAt,
	)
	return i, err
}

const listPostingHistoryByPosting = `-- name: ListPostingHistoryByPosting :many
SELECT id, posting_id, change_type, snapshot, recorded_at FROM posting_history
WHERE posting_id = ?
ORDER BY recorded_at
`

func (q *Queries) ListPostingHistoryByPosting(ctx context.Context, postingID int64) ([]PostingHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPostingHistoryByPosting, postingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostingHistory
	for rows.Next() {
		var i PostingHistory
		if err := rows.Scan(
			&i.ID,
			&i.PostingID,
			&i.ChangeType,
			&i.Snapshot,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
