// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posting_markup.sql

package db

import (
	"context"
)

const archivePosting = `-- name: ArchivePosting :one
UPDATE posting_markup
SET archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

func (q *Queries) ArchivePosting(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, archivePosting, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPostingMarkup = `-- name: CreatePostingMarkup :one
INSERT INTO posting_markup (posting_id)
VALUES (?)
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

// Not exposed directly on the Store API: every posting must have exactly
// one markup row, so Store creates it as part of UpsertPosting rather than
// leaving callers to remember a second call. Relies on column defaults
// (interested_at=NULL, archived_at=NULL, notes=”).
func (q *Queries) CreatePostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, createPostingMarkup, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostingMarkup = `-- name: GetPostingMarkup :one
SELECT posting_id, interested_at, archived_at, notes, created_at, updated_at FROM posting_markup
WHERE posting_id = ?
`

func (q *Queries) GetPostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, getPostingMarkup, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPostingInterested = `-- name: MarkPostingInterested :one
UPDATE posting_markup
SET interested_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

func (q *Queries) MarkPostingInterested(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, markPostingInterested, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchivePosting = `-- name: UnarchivePosting :one
UPDATE posting_markup
SET archived_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

func (q *Queries) UnarchivePosting(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, unarchivePosting, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unmarkPostingInterested = `-- name: UnmarkPostingInterested :one
UPDATE posting_markup
SET interested_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

func (q *Queries) UnmarkPostingInterested(ctx context.Context, postingID int64) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, unmarkPostingInterested, postingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePostingMarkupNotes = `-- name: UpdatePostingMarkupNotes :one
UPDATE posting_markup
SET notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE posting_id = ?
RETURNING posting_id, interested_at, archived_at, notes, created_at, updated_at
`

type UpdatePostingMarkupNotesParams struct {
	Notes     string `json:"notes"`
	PostingID int64  `json:"posting_id"`
}

func (q *Queries) UpdatePostingMarkupNotes(ctx context.Context, arg UpdatePostingMarkupNotesParams) (PostingMarkup, error) {
	row := q.db.QueryRowContext(ctx, updatePostingMarkupNotes, arg.Notes, arg.PostingID)
	var i PostingMarkup
	err := row.Scan(
		&i.PostingID,
		&i.InterestedAt,
		&i.ArchivedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
