// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	GetCompany(ctx context.Context, id int64) (Company, error)
	ListActiveCompanies(ctx context.Context) ([]Company, error)
	RestoreCompany(ctx context.Context, id int64) error
	SoftDeleteCompany(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
