// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddTagToPosting(ctx context.Context, arg AddTagToPostingParams) error
	CountDocumentReviews(ctx context.Context, arg CountDocumentReviewsParams) (int64, error)
	// Unlike posting_markup, not auto-created for every posting -- an
	// application exists only once the user takes an explicit "start
	// application" action. status is supplied explicitly by the caller
	// (store.CreateApplication passes store.ApplicationStatusStarted.String())
	// rather than relying on a DB default -- the initial value is the
	// application's decision, not the schema's (see db/migrations/00004_...,
	// PR #17 review). notes still relies on its own column default ('').
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateCompanyFilter(ctx context.Context, arg CreateCompanyFilterParams) (CompanyFilter, error)
	CreateDocumentReview(ctx context.Context, arg CreateDocumentReviewParams) (DocumentReview, error)
	CreateInterviewStage(ctx context.Context, arg CreateInterviewStageParams) (InterviewStage, error)
	CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error)
	CreatePostingHistory(ctx context.Context, arg CreatePostingHistoryParams) (PostingHistory, error)
	// Not exposed directly on the Store API: every posting must have exactly
	// one markup row, so Store creates it as part of UpsertPosting rather than
	// leaving callers to remember a second call. Relies on column defaults
	// (interested_at=NULL, archived_at=NULL, notes='').
	CreatePostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	DeleteCompanyFilters(ctx context.Context, companyID int64) error
	DeleteInterviewStage(ctx context.Context, id int64) error
	GetApplication(ctx context.Context, postingID int64) (Application, error)
	GetCompany(ctx context.Context, id int64) (Company, error)
	// Deliberately ignores deleted_at: source+source_ref is UNIQUE across all
	// rows regardless of soft-delete state, so re-adding a company (CreateCompany)
	// needs to find a soft-deleted match too, in order to restore it instead of
	// violating the UNIQUE constraint with a duplicate insert.
	GetCompanyBySourceAndSourceRef(ctx context.Context, arg GetCompanyBySourceAndSourceRefParams) (Company, error)
	GetPosting(ctx context.Context, id int64) (Posting, error)
	GetPostingBySourceAndSourceID(ctx context.Context, arg GetPostingBySourceAndSourceIDParams) (Posting, error)
	GetPostingMarkup(ctx context.Context, postingID int64) (PostingMarkup, error)
	// Not filtered on deleted_at: used for existence checks (e.g. before
	// creating) where callers need to know about a soft-deleted tag too, not
	// just active ones.
	GetTagByName(ctx context.Context, name string) (Tag, error)
	// Applications not at a terminal dead-end status, joined with their
	// posting and company name -- feeds the active-applications TUI screen
	// (#43). Unlike ListInterestedPostings this is an inner join on
	// applications (an application always exists for every row here),
	// ordered most-recently-changed first so whatever moved last surfaces
	// at the top.
	//
	// sqlc.embed(applications)/sqlc.embed(postings) generate nested
	// Application/Posting fields on the row directly from the schema, rather
	// than us hand-selecting+aliasing individual columns and reconstructing
	// them field-by-field in Go -- verified this works cleanly on this
	// engine (sqlite, sqlc v1.31.1) alongside a plain aliased column, one
	// inner join, no collisions (see decisions.log, ApplicationView).
	//
	// sqlc.slice('terminal_statuses') keeps store.TerminalApplicationStatuses
	// as the sole source of truth for which statuses are terminal -- no
	// status strings are hardcoded here, they're passed in as a query
	// parameter at call time (see decisions.log, issue #60). Verified this
	// works correctly on this engine with real data before adopting it; the
	// one real constraint is that sqlc.slice can't safely combine with other
	// bound parameters on sqlite (a documented ordering bug) -- this query
	// has none today, but that needs re-verifying if one is ever added.
	ListActiveApplications(ctx context.Context, terminalStatuses []sql.NullString) ([]ListActiveApplicationsRow, error)
	ListActiveCompanies(ctx context.Context) ([]Company, error)
	ListCompanyFilters(ctx context.Context, companyID int64) ([]CompanyFilter, error)
	// Keyspace discovery for filter selection: department is a company-
	// specific vocabulary (not a fixed enum), so filter values are offered
	// from what's actually been ingested, not guessed at. No "IS NOT NULL"
	// check needed -- department is NOT NULL DEFAULT '' (see decisions.log,
	// #74), so excluding '' is the only filter required.
	ListDistinctDepartmentsForCompany(ctx context.Context, companyID int64) ([]string, error)
	ListDistinctLocationsForCompany(ctx context.Context, companyID int64) ([]string, error)
	// cycle DESC: most recent review first, matching how a human would want
	// to read review history (latest verdict up top).
	ListDocumentReviews(ctx context.Context, arg ListDocumentReviewsParams) ([]DocumentReview, error)
	// Postings the user has flagged interested and not archived, joined with
	// their company name and -- if one has been started -- their
	// application's id and status. Feeds the stage package's discovery of
	// work for the external-agent hand-off mechanism (see stage.List).
	//
	// sqlc.embed(postings) for the always-present side (postings is inner-
	// joined via posting_markup, never nullable here) -- same reasoning as
	// ListActiveApplications (see decisions.log, ApplicationView). Deliberately
	// NOT sqlc.embed(applications): that side is LEFT JOINed (an application
	// may not exist yet) and sqlc.embed has a documented bug scanning a NULL
	// embedded struct on sqlite (sqlc-dev/sqlc#2997) -- kept as individually
	// aliased nullable columns, handled by the existing sql.NullInt64/
	// sql.NullString .Valid checks in interestedPostingFromRow.
	ListInterestedPostings(ctx context.Context) ([]ListInterestedPostingsRow, error)
	ListInterviewStagesByApplication(ctx context.Context, applicationID int64) ([]InterviewStage, error)
	ListPostingHistoryByPosting(ctx context.Context, postingID int64) ([]PostingHistory, error)
	// id DESC is a tiebreaker: a single sync inserts many rows within the same
	// CURRENT_TIMESTAMP second (sqlite has only second resolution), so
	// first_seen_at alone leaves ties with no guaranteed order.
	ListPostingsByCompany(ctx context.Context, companyID int64) ([]Posting, error)
	// Active tags only: this is the pick list for tagging postings, and a
	// soft-deleted tag shouldn't be offered for new use.
	ListTags(ctx context.Context) ([]Tag, error)
	// Not filtered on deleted_at: a posting's existing tag associations are
	// historical record and should keep showing even if the tag itself was
	// later soft-deleted (see schema comment on posting_tags).
	ListTagsForPosting(ctx context.Context, postingID int64) ([]Tag, error)
	MarkPostingClosed(ctx context.Context, id int64) error
	MarkPostingReopened(ctx context.Context, id int64) error
	RemoveTagFromPosting(ctx context.Context, arg RemoveTagFromPostingParams) error
	RestoreCompany(ctx context.Context, id int64) error
	RestoreCompanyWithName(ctx context.Context, arg RestoreCompanyWithNameParams) (Company, error)
	// See SetPostingInterested -- same mutual-exclusivity reasoning, mirrored.
	SetPostingArchived(ctx context.Context, postingID int64) (PostingMarkup, error)
	// Sets interested_at and also clears archived_at: the TUI treats
	// interested/archived as mutually exclusive from the user's perspective
	// (pressing "interested" while archived switches state rather than
	// stacking), even though the schema itself allows both to be set.
	SetPostingInterested(ctx context.Context, postingID int64) (PostingMarkup, error)
	SoftDeleteCompany(ctx context.Context, id int64) error
	SoftDeleteTag(ctx context.Context, id int64) error
	UnarchivePosting(ctx context.Context, postingID int64) (PostingMarkup, error)
	UnmarkPostingInterested(ctx context.Context, postingID int64) (PostingMarkup, error)
	UpdateApplicationNotes(ctx context.Context, arg UpdateApplicationNotesParams) (Application, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (Application, error)
	// Excludes soft-deleted rows, same guard as GetCompany -- editing a
	// deleted company isn't a supported action.
	UpdateCompanyName(ctx context.Context, arg UpdateCompanyNameParams) (Company, error)
	UpdateInterviewStage(ctx context.Context, arg UpdateInterviewStageParams) (InterviewStage, error)
	UpdateInterviewStageOutcome(ctx context.Context, arg UpdateInterviewStageOutcomeParams) (InterviewStage, error)
	// Updates ingested content fields only. Deliberately does not touch
	// listing_status: transitions between open/closed are explicit domain
	// decisions (see MarkPostingClosed/MarkPostingReopened), not a side effect
	// of re-ingesting content. Does not touch company_id: a given (source,
	// source_id) is assumed to belong to the same company for its lifetime.
	UpdatePosting(ctx context.Context, arg UpdatePostingParams) (Posting, error)
	UpdatePostingMarkupNotes(ctx context.Context, arg UpdatePostingMarkupNotesParams) (PostingMarkup, error)
}

var _ Querier = (*Queries)(nil)
