// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
)

const addTagToPosting = `-- name: AddTagToPosting :exec
INSERT INTO posting_tags (posting_id, tag_id)
VALUES (?, ?)
`

type AddTagToPostingParams struct {
	PostingID int64 `json:"posting_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddTagToPosting(ctx context.Context, arg AddTagToPostingParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPosting, arg.PostingID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
RETURNING id, name, deleted_at, created_at, updated_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, deleted_at, created_at, updated_at FROM tags
WHERE name = ?
`

// Not filtered on deleted_at: used for existence checks (e.g. before
// creating) where callers need to know about a soft-deleted tag too, not
// just active ones.
func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, deleted_at, created_at, updated_at FROM tags
WHERE deleted_at IS NULL
ORDER BY name
`

// Active tags only: this is the pick list for tagging postings, and a
// soft-deleted tag shouldn't be offered for new use.
func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForPosting = `-- name: ListTagsForPosting :many
SELECT t.id, t.name, t.deleted_at, t.created_at, t.updated_at FROM tags t
JOIN posting_tags pt ON pt.tag_id = t.id
WHERE pt.posting_id = ?
ORDER BY t.name
`

// Not filtered on deleted_at: a posting's existing tag associations are
// historical record and should keep showing even if the tag itself was
// later soft-deleted (see schema comment on posting_tags).
func (q *Queries) ListTagsForPosting(ctx context.Context, postingID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForPosting, postingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromPosting = `-- name: RemoveTagFromPosting :exec
DELETE FROM posting_tags
WHERE posting_id = ? AND tag_id = ?
`

type RemoveTagFromPostingParams struct {
	PostingID int64 `json:"posting_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPosting(ctx context.Context, arg RemoveTagFromPostingParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPosting, arg.PostingID, arg.TagID)
	return err
}

const softDeleteTag = `-- name: SoftDeleteTag :exec
UPDATE tags
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTag, id)
	return err
}
